name: Bug Report
description: File a bug report to help us improve
title: "[Bug]: "
labels: ["bug", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!

  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: A clear and concise description of what the bug is.
      placeholder: Tell us what went wrong!
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
      placeholder: What should have happened?
    validations:
      required: true

  - type: textarea
    id: reproduce
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. Scroll down to '...'
        4. See error
    validations:
      required: true

  - type: dropdown
    id: severity
    attributes:
      label: Severity
      description: How severe is this bug?
      options:
        - Critical (app crashes/unusable)
        - High (major feature broken)
        - Medium (feature partially broken)
        - Low (minor issue/cosmetic)
    validations:
      required: true

  - type: dropdown
    id: platform
    attributes:
      label: Platform
      description: What platform(s) does this occur on?
      multiple: true
      options:
        - Windows
        - Linux (X11)
        - Linux (Wayland)
        - macOS
    validations:
      required: true

  - type: input
    id: version
    attributes:
      label: Version
      description: What version of Open WhisperFlow are you running?
      placeholder: "e.g., 0.1.0"
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Relevant Log Output
      description: Please copy and paste any relevant log output (RUST_LOG=debug)
      render: shell

  - type: textarea
    id: context
    attributes:
      label: Additional Context
      description: Add any other context about the problem here
      placeholder: Screenshots, configuration, etc.

  - type: checkboxes
    id: checklist
    attributes:
      label: Pre-submission Checklist
      description: Please verify the following before submitting
      options:
        - label: I have searched for similar issues and this is not a duplicate
          required: true
        - label: I have read the documentation
          required: true
        - label: I have checked TODO.md for known issues
          required: true
