name: Documentation Issue
description: Report an issue with documentation
title: "[Docs]: "
labels: ["documentation"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for helping improve our documentation!

  - type: dropdown
    id: doc-type
    attributes:
      label: Documentation Type
      description: What type of documentation needs improvement?
      options:
        - User Guide (README.md)
        - Developer Guide (CLAUDE.md)
        - Architecture Documentation (ARCHITECTURE.md)
        - API Documentation (code comments)
        - Contributing Guide (CONTRIBUTING.md)
        - Other
    validations:
      required: true

  - type: textarea
    id: issue
    attributes:
      label: What's the Issue?
      description: What's wrong, missing, or unclear in the documentation?
      placeholder: The documentation for X is unclear because...
    validations:
      required: true

  - type: textarea
    id: location
    attributes:
      label: Location
      description: Where is this documentation issue? (file path, section, line number)
      placeholder: "e.g., README.md, line 42, Installation section"
    validations:
      required: true

  - type: textarea
    id: suggestion
    attributes:
      label: Suggested Improvement
      description: How should the documentation be improved?
      placeholder: It should say...

  - type: checkboxes
    id: willing
    attributes:
      label: Contribution
      options:
        - label: I am willing to submit a PR to fix this
